// ==========================================
// Banco de Textos para Leitura em Voz Alta
// ==========================================
// Adicione mais textos seguindo o formato:
// { titulo: "Título do texto", texto: "Texto em italiano...", nivel: "qa|vital-frosi" }

const textos = [

    {
        titulo: "Introduzione all'automazione dei test",
        texto: "L'automazione dei test consiste nell'usare strumenti software specializzati per eseguire automaticamente verifiche su applicazioni. Invece di navigare manualmente l'applicazione e controllare i risultati, i test automatizzati eseguono script che simulano le azioni dell'utente e confrontano gli esiti con i risultati attesi. I principali vantaggi sono esecuzione più rapida, risultati coerenti e la possibilità di ripetere i test senza intervento umano. L'automazione è particolarmente utile per i test di regressione, quando gli stessi test vanno eseguiti più volte dopo modifiche al codice. Framework popolari includono Playwright, Cypress e Selenium, ciascuno con punti di forza adatti a tipi diversi di applicazioni. Ad esempio, Playwright eccelle nei test cross‑browser e offre un ottimo supporto per applicazioni web moderne. All'inizio è importante capire che non tutti i test devono essere automatizzati: i test manuali restano fondamentali per esplorazione e valutazione dell'usabilità. La chiave è trovare il giusto equilibrio tra test automatici e manuali in base alle esigenze del progetto. Una buona strategia di automazione considera manutenibilità, tempi di esecuzione e il costo di creazione/aggiornamento dei test. Team che adottano correttamente l'automazione spesso osservano miglioramenti significativi nei cicli di rilascio e nella qualità del software.",
        traducao: "Automação de testes é a prática de usar ferramentas de software especializadas para executar testes em aplicações de software automaticamente. Em vez de clicar manualmente através de uma aplicação e verificar resultados, testes automatizados podem executar scripts que simulam interações do usuário e verificam resultados contra resultados esperados.",
        nivel: "qa"
    },
    {
        titulo: "Primi passi con Playwright",
        texto: "Playwright è un moderno framework end‑to‑end sviluppato da Microsoft che supporta i principali browser (Chromium, Firefox e WebKit) con un'unica API. Una delle sue caratteristiche più utili è l'auto‑wait, che attende automaticamente che gli elementi siano interagibili prima di eseguire un'azione, riducendo i test flaky. Per iniziare serve Node.js; puoi creare un progetto con il comando npm init playwright, che genera la struttura base, i file di configurazione e esempi di test. I test Playwright si scrivono in JavaScript o TypeScript: una struttura tipica importa le funzioni test ed expect dal pacchetto Playwright. I test sono organizzati in blocchi test che descrivono il comportamento atteso. L'oggetto page è il principale strumento per interagire con le pagine: navigare URL, cliccare, compilare form e verificare condizioni. Playwright offre anche strumenti di debug potenti, come l'Inspector e il trace viewer, utili per capire perché un test fallisce. La funzione codegen registra le interazioni nel browser e genera codice di test automaticamente, ottima per imparare l'API mentre si crea codice reale.",
        traducao: "Playwright é um framework moderno de testes end-to-end desenvolvido pela Microsoft. Ele suporta todos os principais navegadores incluindo Chromium, Firefox e WebKit com uma única API.",
        nivel: "qa"
    },
    {
        titulo: "Scrivere il tuo primo test con Playwright",
        texto: "Scrivere il primo test con Playwright è semplice una volta compresa la struttura di base. Un file di test tipico importa le funzioni necessarie (test, expect). La funzione test prende una descrizione e una callback async in cui inserire la logica. All'interno del test si riceve l'oggetto page che rappresenta una pagina del browser. Si naviga con page.goto, si interagisce con gli elementi tramite locator e si verificano i risultati con le assertion. Playwright suggerisce di usare attributi come data-testid per selezioni stabili; i locator accettano selector CSS, testo e ruoli di accessibilità. Le assertion (es. toBeVisible, toHaveText, toHaveURL) attendono automaticamente la condizione, rendendo i test più affidabili. I test dovrebbero essere indipendenti: ogni test prepara i propri dati e pulisce lo stato; per setup/teardown usare beforeEach/afterEach. Organizza i test con describe e nomi descrittivi per facilitare manutenzione e diagnosi degli errori.",
        traducao: "Escrever seu primeiro teste com Playwright é simples uma vez que você entende a estrutura básica. Um arquivo de teste típico começa importando as funções necessárias do Playwright.",
        nivel: "qa"
    },
    {
        titulo: "Pattern Page Object Model",
        texto: "Il Page Object Model è un pattern di progettazione molto diffuso nell'automazione dei test per rendere il codice manutenibile e riutilizzabile. L'idea è incapsulare elementi e azioni specifiche di una pagina in classi dedicate: ogni pagina o componente ha una classe con i locator e i metodi per interagirvi. I vantaggi includono riduzione della duplicazione, maggiore manutenibilità (se cambia l'interfaccia si aggiorna il page object invece di tutti i test) e test più leggibili grazie ad API significative. In Playwright i page object sono classi che ricevono la page nel costruttore; le proprietà definiscono i locator e i metodi incapsulano azioni comuni (login, compilazione form, navigazione). I test istanziano questi oggetti e chiamano i metodi, separando responsabilità e rendendo la suite più scalabile.",
        traducao: "O Page Object Model é um padrão de design amplamente usado em automação de testes para criar código de teste manutenível e reutilizável.",
        nivel: "qa"
    },
    {
        titulo: "Test API con Playwright",
        texto: "Playwright non è solo per test di UI. Offre anche potenti funzionalità per i test API attraverso il request context. I test API sono più veloci di quelli UI e verificano direttamente la logica backend senza passare dall'interfaccia utente. Per eseguire test API si crea un request context usando la fixture request o creandone uno manualmente. L'oggetto request fornisce metodi per tutti i verbi HTTP comuni: GET, POST, PUT, PATCH e DELETE. Ogni metodo restituisce un oggetto response che si può ispezionare per status code, header e body. Un test API tipico invia una richiesta e verifica la risposta. Ad esempio, una POST per creare una risorsa, verificando che lo status sia 201 e che il body contenga i dati attesi. Il metodo response.json fa il parsing automatico del JSON. I test API sono ottimi per preparare dati prima dei test UI: anziché compilare form per creare utenti o prodotti di test, si fanno chiamate API dirette, accelerando l'esecuzione. Si può anche combinare API e UI nello stesso file di test: usare le API per impostare lo stato, poi verificare con la UI che i dati siano visualizzati correttamente.",
        traducao: "O Playwright não é apenas para testes de UI. Ele também fornece capacidades poderosas para testes de API através de sua funcionalidade de request context. Testes de API são mais rápidos que testes de UI e podem verificar funcionalidades do backend diretamente.",
        nivel: "qa"
    },
    {
        titulo: "Strategie di gestione dei dati di test",
        texto: "Una gestione efficace dei dati di test è fondamentale per una suite affidabile. I test hanno bisogno di dati, ma dati hardcoded sparsi nei file diventano un incubo da mantenere. Una strategia ben progettata mantiene i test puliti, indipendenti e facili da aggiornare. Un approccio comune sono i file di fixture: set predefiniti di dati memorizzati in file separati, spesso in JSON. I test importano le fixture per popolare form o verificare risultati. Questo centralizza i dati e semplifica gli aggiornamenti. Un altro approccio usa funzioni factory che generano dati dinamicamente. Le factory creano dati casuali ma validi, assicurando che ogni esecuzione usi valori unici. Librerie come Faker generano nomi, email e indirizzi realistici. Per test che richiedono stato nel database, si può usare seeding o chiamate API prima dell'esecuzione. Gli hook beforeAll e beforeEach sono perfetti per il setup. Ricordarsi di pulire i dati dopo i test per mantenere l'ambiente ordinato. Le variabili d'ambiente sono utili per configurazioni che variano tra ambienti. Archiviare dati sensibili come chiavi API in variabili d'ambiente anziché nel codice. Playwright supporta file dotenv per lo sviluppo locale.",
        traducao: "Gerenciamento eficaz de dados de teste é crítico para manter uma suíte de testes confiável. Testes precisam de dados para trabalhar, mas dados hardcoded espalhados por arquivos de teste se tornam um pesadelo de manutenção.",
        nivel: "qa"
    },
    {
        titulo: "Debug dei test falliti",
        texto: "Anche i test meglio scritti falliscono a volte. Saper fare debug in modo efficiente è una competenza essenziale per ogni QA engineer. Playwright offre diversi strumenti potenti per capire perché un test fallisce. Il primo è il Playwright Inspector, avviabile con la flag debug. L'Inspector permette di scorrere il test riga per riga, ispezionare lo stato della pagina e vedere esattamente cosa fa Playwright. Si può mettere in pausa l'esecuzione ed esplorare gli elementi. I file trace sono un'altra risorsa preziosa. Quando abilitati, Playwright registra una traccia completa dell'esecuzione includendo screenshot, snapshot del DOM, richieste di rete e log della console. Il Trace Viewer mostra una timeline di tutte le azioni. Questo è particolarmente utile per debug di test che falliscono in CI ma passano in locale. Screenshot e video catturano lo stato della pagina quando i test falliscono. Configurare Playwright per salvare automaticamente questi artefatti. I log della console e delle richieste di rete forniscono contesto aggiuntivo. Il metodo page.on permette di ascoltare messaggi e eventi durante l'esecuzione. Quando si fa debug, prima riprodurre il fallimento in modo consistente, poi capire la causa radice anziché correggere solo i sintomi.",
        traducao: "Mesmo os testes melhor escritos falham às vezes. Saber como depurar testes que falharam eficientemente é uma habilidade essencial para qualquer engenheiro de QA.",
        nivel: "qa"
    },
    {
        titulo: "Integrazione Continua per i test",
        texto: "L'Integrazione Continua è la pratica di eseguire automaticamente i test ogni volta che il codice viene pushato in un repository. Configurare la CI per i test Playwright garantisce che i bug vengano trovati presto e la suite resti sana. La maggior parte dei team usa servizi CI come GitHub Actions, GitLab CI, Jenkins o CircleCI. Per configurare Playwright in CI bisogna installare le dipendenze, scaricare i binari dei browser e far girare i test in ambiente headless. Playwright fornisce un template di workflow per GitHub Actions. La configurazione chiave è eseguire i browser in modalità headless poiché i server CI di solito non hanno display. La pipeline CI dovrebbe eseguire i test su ogni pull request prima del merge. Questo vincola il merge al successo dei test, impedendo al codice rotto di entrare nel branch principale. L'esecuzione parallela velocizza le run CI. Playwright supporta lo sharding, che distribuisce i test su più worker. Ogni worker esegue una parte della suite e i risultati vengono aggregati alla fine. Questo può ridurre una run di 30 minuti a pochi minuti. Configurare la pipeline per salvare report, screenshot e trace quando i test falliscono. Molti team generano anche report HTML per una panoramica visuale. Considerare run pianificate oltre ai trigger sulle pull request.",
        traducao: "Integração Contínua é a prática de executar testes automaticamente sempre que mudanças de código são enviadas para um repositório. Configurar CI para seus testes Playwright garante que bugs sejam capturados cedo.",
        nivel: "qa"
    },
    {
        titulo: "Best practice per l'automazione dei test",
        texto: "Seguire le best practice porta a una suite di test manutenibile, affidabile e di valore. Queste pratiche sono state affinate dalla community nel corso degli anni. Scrivi test indipendenti che possano girare in qualsiasi ordine. Ogni test deve preparare le proprie precondizioni senza dipendere dallo stato di altri test. Questo rende i test più affidabili e permette l'esecuzione parallela. Usa hook beforeEach per il setup comune. Mantieni i test focalizzati su un singolo comportamento. Un test che verifica troppe cose è difficile da capire e mantenere. Quando fallisce, bisogna investigare molteplici cause. Scrivi invece test piccoli che verifichino un aspetto specifico. Usa nomi significativi per test e blocchi describe. Un buon nome spiega quale comportamento viene verificato senza leggere il codice. Evita i test flaky a tutti i costi. Test che a volte passano e a volte falliscono distruggono la fiducia nella suite. Quando incontri flakiness, correggi subito. Usa i meccanismi di attesa di Playwright e evita sleep arbitrari. Rivedi e refactora i test regolarmente. Elimina test che non danno più valore. Consolida test simili con la parametrizzazione. Tratta il codice di test con la stessa cura del codice di produzione: usa controllo versione, code review e standard di codifica consistenti.",
        traducao: "Seguir boas práticas em automação de testes leva a uma suíte de testes manutenível, confiável e valiosa. Essas práticas foram refinadas pela comunidade de testes ao longo de anos de experiência.",
        nivel: "qa"
    },
    {
        titulo: "Test cross-browser",
        texto: "I test cross-browser verificano che l'applicazione funzioni correttamente su diversi browser. Gli utenti accedono ai siti da Chrome, Firefox, Safari, Edge e altri, ciascuno con il proprio motore di rendering e implementazione JavaScript. Le differenze tra browser possono causare bug visibili solo per certi utenti. Playwright rende semplice il testing cross-browser supportando Chromium, Firefox e WebKit con un'unica API. Si scrivono i test una volta e si eseguono su tutti i browser. Il file di configurazione di Playwright permette di definire più progetti, ciascuno per un browser diverso. Tuttavia, eseguire ogni test su ogni browser spesso non è pratico per vincoli di tempo. Una strategia comune è eseguire la suite completa sul browser principale (Chrome) per feedback rapido, e un sottoinsieme di test critici su tutti i browser, magari di notte o prima dei rilasci. Playwright può anche emulare dispositivi mobile inclusi viewport, user agent e touch event. Questo non sostituisce i test su dispositivi reali, ma cattura molti problemi specifici mobile. Playwright scarica versioni specifiche dei browser per risultati consistenti. In CI assicurarsi di testare le versioni effettivamente usate dagli utenti. L'obiettivo è riduzione del rischio, non la perfezione su ogni combinazione di versione.",
        traducao: "Testes cross-browser verificam que sua aplicação funciona corretamente em diferentes navegadores web. Usuários acessam websites do Chrome, Firefox, Safari, Edge e outros navegadores.",
        nivel: "qa"
    },
    {
        titulo: "Test di regressione visuale",
        texto: "I test di regressione visuale rilevano cambiamenti involontari nell'aspetto dell'applicazione. Mentre i test funzionali verificano che le feature funzionino, potrebbero non notare bug visivi come pulsanti disallineati, colori sbagliati o layout rotti. I test visuali confrontano screenshot con immagini baseline per rilevare differenze. Playwright offre supporto nativo tramite l'assertion toHaveScreenshot. Alla prima esecuzione salva uno screenshot baseline. Nelle esecuzioni successive cattura un nuovo screenshot e lo confronta con il baseline. Se le immagini differiscono oltre una soglia configurabile, il test fallisce. Implementare test visuali richiede alcune decisioni. Decidere cosa catturare: screenshot a pagina intera rilevano più problemi ma sono più soggetti a falsi positivi da contenuto dinamico. Screenshot a livello di componente sono più stabili. Si possono mascherare elementi dinamici come timestamp o pubblicità. Gestire le immagini baseline è cruciale. Archiviarle nel controllo versione. Quando le modifiche visive sono intenzionali, aggiornare i baseline con la flag update snapshots. I test visuali sono sensibili all'ambiente. Il rendering può variare tra sistemi operativi. Per risultati consistenti usare ambienti controllati come container Docker. Usare i test visuali come complemento ai test funzionali, non come sostituto.",
        traducao: "Testes de regressão visual detectam mudanças não intencionais na aparência da sua aplicação. Enquanto testes funcionais verificam que funcionalidades trabalham corretamente, eles podem perder bugs visuais.",
        nivel: "qa"
    },
    {
        titulo: "Fondamenti di test delle performance",
        texto: "I test delle performance valutano come l'applicazione si comporta sotto varie condizioni: carico, stress e uso normale. Anche se Playwright è principalmente uno strumento di test funzionali, può aiutare a misurare e monitorare le performance. Le metriche di performance web dicono come gli utenti percepiscono l'applicazione. I Core Web Vitals includono Largest Contentful Paint (performance di caricamento), First Input Delay (interattività) e Cumulative Layout Shift (stabilità visiva). Queste metriche impattano soddisfazione utente e ranking sui motori di ricerca. Playwright può raccogliere metriche durante l'esecuzione. Il metodo page.metrics restituisce statistiche di tempo e memoria. Si può accedere alla Performance API tramite page.evaluate. Registrare queste metriche nel tempo per tracciare trend e regressioni. Il throttling di rete simula connessioni lente. Playwright supporta la configurazione di condizioni di rete come latenza e banda. Testare l'applicazione in queste condizioni per assicurarsi che resti usabile. Per test di performance completi, considerare strumenti specializzati come Lighthouse, WebPageTest, k6 o JMeter. Integrare test di performance nella CI con budget che facciano fallire le build quando le metriche chiave superano le soglie. La performance richiede attenzione continua.",
        traducao: "Testes de performance avaliam como sua aplicação se comporta sob várias condições incluindo carga, stress e uso normal. Embora o Playwright seja principalmente uma ferramenta de testes funcionais.",
        nivel: "qa"
    },
    {
        titulo: "Lavorare con i locator",
        texto: "I locator sono il modo in cui Playwright trova gli elementi sulla pagina. Scegliere la strategia giusta è fondamentale per test affidabili e manutenibili. Scelte sbagliate portano a test flaky che si rompono con piccole modifiche UI. Buoni locator sono stabili, unici e significativi. Playwright raccomanda di usare attributi rivolti all'utente anziché dettagli implementativi. Il locator getByRole trova elementi per ruolo di accessibilità, stabile e che assicura accessibilità. Ad esempio, getByRole button con name Submit trova un pulsante etichettato Submit indipendentemente da classi CSS o posizione nel DOM. getByText trova elementi con testo specifico; getByLabel è perfetto per i campi form. Questi locator semantici sono preferiti perché riflettono l'esperienza utente. Gli attributi data-testid forniscono un aggancio dedicato per i test che non cambia quando i designer aggiornano la UI. Il locator getByTestId li targetizza specificamente. Evitare locator che dipendono dalla struttura del documento o dallo stile. Espressioni XPath che navigano tra parent e child si rompono quando la struttura cambia. Selector CSS basati su classi o ID si rompono quando si refactora lo stile. Playwright offre filtraggio dei locator per restringere i risultati quando locator semplici matchano più elementi. Si possono concatenare filtri basati su contenuto testuale, figli specifici o visibilità.",
        traducao: "Locators são como o Playwright encontra elementos em uma página. Escolher a estratégia certa de locator é fundamental para escrever testes confiáveis e manuteníveis.",
        nivel: "qa"
    },
    {
        titulo: "Report e documentazione dei test",
        texto: "Report efficaci comunicano i risultati dei test chiaramente a tutti gli stakeholder. Gli sviluppatori hanno bisogno di informazioni dettagliate per correggere i test che falliscono. I manager hanno bisogno di riepiloghi di alto livello per prendere decisioni. Report ben progettati servono entrambi i pubblici e costruiscono fiducia nel processo di testing. Playwright include un reporter HTML integrato che genera report interattivi dopo le esecuzioni. Il report mostra quali test sono passati, falliti o skippati, insieme a tempo di esecuzione e dettagli degli errori. Si può esplorare ogni singolo test per vedere screenshot, trace e messaggi di errore dettagliati. Oltre ai reporter integrati, Playwright supporta reporter personalizzati e integrazioni con strumenti esterni. Molti team integrano con piattaforme di test management come TestRail, Zephyr o Xray. La documentazione dei test va oltre i report. Mantenere documentazione che spieghi la strategia di testing: cosa è automatizzato, cosa testato manualmente e perché. Documentare come eseguire i test localmente e in CI. Creare guide di onboarding per i nuovi membri del team. Tenere questa documentazione nel controllo versione. I commenti nel codice servono come micro-documentazione. Spiegare perché un test esiste, non solo cosa fa. Rivedere regolarmente la copertura e identificare gap. Documentare le limitazioni note. Il testing è un processo continuo e una buona documentazione supporta il miglioramento continuo.",
        traducao: "Relatórios de teste eficazes comunicam resultados de teste claramente para todos os stakeholders. Desenvolvedores precisam de informações detalhadas para corrigir testes que falham.",
        nivel: "qa"
    }
];
